export type TransactionType = {
    unique_id: string,
    type: string,
    reference_id: string,
    reference_type: string,
    reference_number: string,
    reference: string|null,
    status: string,
    total_amount: number,
    total_amount_before_tax: number,
    total_amount_after_tax: number,
    created_at: string,
    updated_at: string,
    created_by: number,
    text: string|null,
    name: string|null,
}